# This is a basic workflow to help you get started with Actions

name: Repository Dispatch

on:
  repository_dispatch:
    types: [publish-event]

jobs:
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
